### PR TITLE
WIP: spec: Update fixtures to use latest version

### PR DESCRIPTION
**Pull request by lazyfrosch**

### CODE REVIEW

**Comment by bobapple** [comment]
I like it better to test with stable releases instead of the master branch. Maybe we should use all modules from Pupppet Forge instead of GitHub. This way we would ensure we're testing with a stable release version and we wouldn't have to take care about updating version numbers.

**Comment by lazyfrosch** [comment]
@bobapple I get your point, but this actually follows the practice of most of the Puppet modules out there.

See here:

* https://github.com/voxpupuli/puppet-r10k/blob/master/.fixtures.yml
* https://github.com/voxpupuli/puppet-corosync/blob/master/.fixtures.yml
* https://github.com/puppetlabs/puppetlabs-apache/blob/master/.fixtures.yml
* https://github.com/puppetlabs/puppetlabs-mysql/blob/master/.fixtures.yml

They pin only for specific reasons.

**Comment by lazyfrosch** [comment]
@SimonHoenscheid @lbetz opinion?

**Comment by SimonHoenscheid** [comment]
I'm fine with latest Release

**Comment by bobapple** [comment]
I updated fixtures in f60d772031527fa2647d37797c67bf57d44ef6df to retrieve modules from puppet forge

**Pull request closed without merging**
