### PR TITLE
Support Puppet 5 and test it in travis

### LINKED ISSUE #327: puppet 5
Any plans to support Puppet 5?

### LINKED ISSUE #351: Review and update puppetlabs-concat dependency
Hi,

just a question: must the Concat version older than 3.0.0 ? I had to change it, otherwise I wasn't able to upgrade Concat to the latest version for other modules.

cu denny

    { "name": "puppetlabs/concat", "version_requirement": ">= 2.0.1 < 3.0.0" },

### PR DESCRIPTION
**Pull request by lazyfrosch**
* [x] Update dependencies in metadata
* [x] Fix travis issues
* [x] Fix minor spec issues appearing with Puppet 5 (dependency tests)

fixes #327 
resolves #233 
fixes #351

### CODE REVIEW

**Comment by lazyfrosch** [comment]
Not that easy as it seems, not sure what the problem is with the metadata...

**Comment by lazyfrosch** [comment]
Puppet 5 doesn't work with `forge_modules` in fixtures currently: https://tickets.puppetlabs.com/browse/PUP-7738

**Comment by lazyfrosch** [comment]
`forge_modules` have been fixed in Puppet 5.0.1

There seems to be a problem with too much parallel spec processes, also see https://github.com/theforeman/puppet-foreman_proxy/pull/359

**Comment by lazyfrosch** [comment]
There still seems to be problems with concat on Puppet 5:

```
      # Puppet::Parser::Compiler::CatalogValidationError:
      #   Could not find resource 'Concat[/etc/icinga2/features-available/foo.conf]' in parameter 'require' at /home/travis/build/Icinga/puppet-icinga2/spec/fixtures/modules/icinga2/manifests/feature.pp:37
      #   ./vendor/bundle/ruby/2.4.0/gems/puppet-5.0.1/lib/puppet/parser/compiler/catalog_validator/relationship_validator.rb:37:in `block in validate_relationship'
  19) icinga2::feature ubuntu-16.04-x86_64 with ensure => present, feature => foo should contain File[/etc/icinga2/features-enabled/foo.conf] that notifies Class[icinga2::service]
      Failure/Error:
        should contain_file('/etc/icinga2/features-enabled/foo.conf').with({
          'ensure' => 'link',
        }).that_notifies('Class[icinga2::service]')
      
      Puppet::Error:
        Could not find resource 'Concat[/etc/icinga2/features-available/foo.conf]' in parameter 'require' at /home/travis/build/Icinga/puppet-icinga2/spec/fixtures/modules/icinga2/manifests/feature.pp:37 on node testing-docker-4213a8fa-53b7-4e40-b7ea-72851bc829a5.ec2.internal
```

**Comment by lazyfrosch** [comment]
Also see: https://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error

**Comment by lazyfrosch** [comment]
Working on that issue again...

**Comment by cristianbalan-mf** [comment]
Are you working on supporting Puppet 5 but not 4? (https://github.com/Icinga/puppet-icinga2/issues/363 + https://github.com/Icinga/puppet-icinga2/issues/351)

**Comment by lbetz** [comment]
v2.0.0 will support puppet 4 and 5. The difference between 4 and 5 are very less.

**Pull request merged**
