### PR TITLE
enable setting of bind_host and bind_port for feature::api

### PR DESCRIPTION
**Pull request by aschaber1**
usecase: I need to set bind_host to '::' for ipv6 listening.

### CODE REVIEW

**Comment by Reamer** [comment]
Documentation is missing.

**Comment by aschaber1** [comment]
added documentation and parameter validation

**Comment by lazyfrosch** [comment]
LGTM, added spec

Travis failing is not related to that change.

**Comment by Reamer** [comment]
Offtopic:
@lazyfrosch How it is possibly to extend a pullrequest?

**Comment by lazyfrosch** [comment]
@Reamer as a project contributor you see:

    Add more commits by pushing to the feature/api_bind_settings branch on aschaber1/puppet-icinga2.

I can actually directly push to his repository on that branch.

**Pull request merged**
