### PR TITLE
Use Function ensure_packages()

### PR DESCRIPTION
**Pull request by cocker-cc**
- use Function `ensure_packages()` instead of Resource `package {}`
- for `ensure_packages()` use Default-Value for `ensure`

### CODE REVIEW

**Comment by lbetz** [comment]
What's the benefit? The ensure_packages function is always dangerous if it is called with parameters, even if they are metaparameters. That's why manage_packages exists.

**Comment by cocker-cc** [comment]
> What's the benefit? The ensure_packages function is always dangerous if it is called with parameters, even if they are metaparameters. That's why manage_packages exists.

Can You elaborate, where `ensure_packages()` could be dangerous?  Isn't it just a wrapper around `package {}`?  

The benefit is – as always with `ensure_packages()`: In my Profile-Classes I don't have to take Care about installing Package `icinga2`, only because the Module `icinga2` does not check `unless defined(Package['icinga2'])` (as it should).

(I rebased my Branch against  recent `puppet-icinga2(master)`).

**Comment by bobapple** [comment]
@cocker-cc the submitted CLA is invalid, please make sure to fill the forms with real data, thank you!

**Comment by lbetz** [comment]
Because it is not certain which of the set parameters (same parameters with different values) are used.

**Comment by cocker-cc** [comment]
> @cocker-cc the submitted CLA is invalid, please make sure to fill the forms with real data, thank you!

Unfortunately, that's no Option for me.

**Comment by lbetz** [comment]
@cocker-cc please complete the certification process

**Comment by lbetz** [comment]
Ok, then I have to close this PR.

**Pull request closed without merging**
