### PR TITLE
Accept Datatype Sensitive for Secrets

### PR DESCRIPTION
**Pull request by cocker-cc**

### CODE REVIEW

**Comment by lbetz** [comment]
In these cases the data type Sensitive is superfluous because the passwords are made visible again with show_diff.

**Comment by cocker-cc** [comment]
> In these cases the data type Sensitive is superfluous because the passwords are made visible again with show_diff.

What do you mean by "in these cases"?  

To make it clear: My main Goal is not to make Passwords invisible – although this is nice.   

My Effort to make many Component-Modules sensitive-aware is:  As an Author of Profile-Modules I do not want to fiddle with `Sensitive` and `unwrap` at all.  My Passwords come out of Vault, and Vault returns Passwords as `Sensitive[String]`.  I just want to pass over these Passwords to the Component-Modules without any further ado.  I my World the Component-Modules "just have to work".  

In an ideal World even the Component-Module should never use `unwrap`.  In most Cases EPP-Files should be used instead of ERB-Files, because EPP itself is able to handle `Sensitive` natively.

**Comment by cocker-cc** [comment]
I did a `git rebase upstream/master && git push -f`.

**Comment by lbetz** [comment]
Thanks for your detailed explanation. Now I understand and will add your changes to the upcoming release. Fortunately I was able to hold myself back from a release.

**Comment by lbetz** [comment]
What's about keys and certificates for TLS?

**Comment by cocker-cc** [comment]
> What's about keys and certificates for TLS?

I created [this PR](https://github.com/puppetlabs/puppet/pull/8799) for the `regsubst` of SSL-Keys.

**Comment by lbetz** [comment]
refs  #689

**Pull request closed without merging**
