### PR TITLE
Added known issues regarding environment bleed to documentation

### PR DESCRIPTION
**Pull request by zilchms**
Discussed in comments in #689

### CODE REVIEW

**Comment by rweigle** [comment]
Looks good!

**Comment by lbetz** [comment]
Thx so much. Would it be correct to add `puppet generate types --environment xxx` to 2) as todo?

**Comment by rweigle** [comment]
I haven't checked the puppet documentation. In our case "Regenerate all resource types in case you are using environment isolation" was deleting the resources ` rm -rf /etc/puppetlabs/code/environment/xxx/.resource_types/` and `puppet generate types --environment xxx`. I'm not sure if the first step is necessary but probably it should be mentioned.

**Comment by zilchms** [comment]
I am in favor of doing it in your style @rweigle . We can split step 2 in the mentioned two steps. We should be on the saver side in your case.

**Pull request merged**
