### PR TITLE
fix permissions on icinga config directories/files

### PR DESCRIPTION
**Pull request by roock**
fix permissions on icinga config directories/files

### CODE REVIEW

**Comment by bobapple** [comment]
Hi rook,
adding permissions for these files would work fine for all Linux operating sytems. It would however break things on Windows. When we build the intallation/configuration mechanism we decided explicitly to use the permissions that come with the package installation and only to maintain the content of the files. By keeping the default permissions we don't have to take care for each OS explicitly. What do you think?

**Comment by roock** [comment]
okay, I see, I haven't thought about that (never used puppet with windows). The main problem is that in my setup puppet by default sets the permissions of files to owner root / group root and mask 0600 so without my changes, icinga does not even start, because it cannot read the config files. I'll try to reproduce this with an empty testing system

**Comment by bobapple** [comment]
Well, that's strange and interesting. What system are you using? Would be great if you can reproduce it

**Comment by Reamer** [comment]
@roock Maybe you have a global default file Resource?

**Comment by roock** [comment]
@Reamer  that would be the only logical explanation for me too, but i don't have any (at least none that I'm aware of)
@bobapple  I'm using Debian 8 with latest puppet version (puppet-agent 1.8.0-1jessie)

**Comment by bobapple** [comment]
Sorry, I am not able to reproduce this

**Comment by roock** [comment]
Correct, I cannot reproduce this with an test puppet instance too. Sorry my precipitate pull request

**Pull request closed without merging**
