### PR TITLE
Update SLES lib directory

### LINKED ISSUE #283: SLES Lib directory is not architecture specific
On SuSE the constants are architecture specific while the packages do not install the plugins in architecture dependent paths.

Changing [params.pp line 118](https://github.com/Icinga/puppet-icinga2/blob/master/manifests/params.pp#L118) to look like debian instead of redhat solves this.

### PR DESCRIPTION
**Pull request by dgoetz**
This pull request fixes #283 by removing the architecture specific constants

### CODE REVIEW

**Comment by dnsmichi** [comment]
Can you fix the tests too please? :-)

**Review by lazyfrosch — APPROVED** [review]
Should be fine when tests go green. I suppose @dgoetz tested it on SUSE :+1:

**Comment by lazyfrosch** [comment]
Looks like the newest Puppetlabs modules on Forge bring us incompatibility problems with Puppet 3...

:+1: for merging, we should address the Puppet 3 issues in testing elsewhere

**Comment by lazyfrosch** [comment]
See #286

**Pull request merged**
