### PR TITLE
Ownergroupwindows (#437)

### PR DESCRIPTION
**Pull request by MelanieGault**
Hi, 

This PR address localized windows server problem.
I use the same param already used for linux.
If you think it leads to complexity or misunderstanding I can change.

Regards,

### CODE REVIEW

**Comment by MelanieGault** [comment]
Hi,

I don't know how to correct all failed checks because they have noting to do with my changes.

**Comment by lbetz** [comment]
Hi Melanie,

thx for your report. Indeed your changes are ok. Our tests are broken.

But the main problem is to do it right we don't wanna manage the user and group, because then we have to manage every config file or directory. Of course I see your Problem with languages like french.

At the moment I havn't any idea to solve this 'feature'.

Bye Lennart

**Comment by MelanieGault** [comment]
Hi Lennart,

Just document well that this module does NOT manage all rights on all files should be a first step before doing something clever.
The installer install with localized owner/group, so everything is OK except the 2 resources changed in the commit. Perhaps do not have owner/group for these resources ?

I don't have any clever idea for now :)

Regards,
Melanie

**Comment by MelanieGault** [comment]
The first run is ok but not the modifications run. So I close this PR and will do another on while everything will be OK !

**Pull request closed without merging**
