### PR TITLE
Update protection of private classes from direct use

### LINKED ISSUE #333: protection of private classes is wrong
if defined($caller_module_name) and $module_name != $caller_module_name and $caller_module_name != '' {
    fail("icinga2::feature is a private define resource of the module icinga2, you're not permitted to use it.")
  }

should be 

if !defined(...) or $module_name != ...

to prevent a call from outside any class and from other modules.

### PR DESCRIPTION
**Pull request by lbetz**
fixes #333

### CODE REVIEW

**Comment by baurmatt** [comment]
Can't we just use [assert_private](https://github.com/puppetlabs/puppetlabs-stdlib#assert_private)?

**Comment by lbetz** [comment]
Pretty good idea. We started with a much earlier version of stdlib without this function. Now we've a dependency on version 4.16.0... but I'm not sure that will fix the unit tests.

**Comment by baurmatt** [comment]
This is also a major improve when it comes to the icinga2::object class. The defined() variant is a lot slower then assert_private(). This is especillay import for setups which might include hundreds/thousands of icinga2::object's.

**Comment by baurmatt** [comment]
The problem with the tests is, that the assert_private() needs to be fake. This should do the trick:

```ruby
  before(:each) do
    # Fake assert_private function from stdlib to not fail within this test
    Puppet::Parser::Functions.newfunction(:assert_private, :type => :rvalue) { |args|
    }
  end
```

**Comment by lazyfrosch** [comment]
Thanks @baurmatt, I incorporated your example

**Pull request merged**
