### PR TITLE
Fix rubocop LineLength # see https://rubocop.readthedocs.io/en/latest…

### PR DESCRIPTION
**Pull request by thomas-merz**
…/cops_layout/#layoutlinelength

### CODE REVIEW

**Comment by thomas-merz** [comment]
Hi @lbetz , I'm missing my commit in master!? What happened to it, where has it gone?

**Comment by lbetz** [comment]
I have no idea.

**Comment by lbetz** [comment]
Very strange.

**Comment by thomas-merz** [comment]
@lbetz Can you please check where commit [0a9e0facf893d263b1c313464ff947ffaa3a6568](https://github.com/Icinga/puppet-icinga2/pull/611/commits/0a9e0facf893d263b1c313464ff947ffaa3a6568) has gone to and merge it into master (if a merge would be ok for you)?

**Comment by lbetz** [comment]
Couldn't find the commit. So I fixed it by hand.

**Pull request merged**
